### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by Nomination-NRB** [felixsanz/felixsanz_dev#1]
The stable diffusion column helped me a lot after I read it, but I still need to learn, and it would be nice to see a blog of your quality.
Are there any plans to update the article on how to train stable diffusion or next steps

**Comment by felixsanz** [comment]
> The stable diffusion column helped me a lot after I read it, but I still need to learn, and it would be nice to see a blog of your quality. Are there any plans to update the article on how to train stable diffusion or next steps

Hello! Thanks for reading the articles :) Yes, I plan to write about training, Stable Diffusion 3, etc... but I need 50 hour days 😁

**Comment by Nomination-NRB** [comment]
> > The stable diffusion column helped me a lot after I read it, but I still need to learn, and it would be nice to see a blog of your quality. Are there any plans to update the article on how to train stable diffusion or next steps
> 
> Hello! Thanks for reading the articles :) Yes, I plan to write about training, Stable Diffusion 3, etc... but I need 50 hour days 😁

follow you~
